name: Simple CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building the project..."

      - name: Test
        run: echo "Running tests..."

      - name: Deploy        
        run: echo "Deploying the project..."

      - name: Current Date and Time
        run: date

      - name: Branch Name
          run: echo "Branch: ${{ github.ref_name }}"

      - name: List Files
        run: ls -la

      - name: Runner OS
        run: echo "Operating System: $RUNNER_OS"
          
