name: Hello

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions"

      - name: Current Date and Time
        run: date

      - name: Branch Name
        run: echo "Branch: ${{ github.ref_name }}"

      - name: List Files
        run: ls -la

      - name: Runner OS
        run: echo "Operating System: $RUNNER_OS"
        
