name: Multi Job Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Step
        run: echo "Building the app"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Test Step
        run: echo "Running tests"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Step
        run: echo "Deploying"
